services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: smpt_sqlserver
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SQLSERVER_PASSWORD}
      MSSQL_PID: Express
    ports:
      - "1433:1433"
    volumes:
      - smpt_sqlserver_data:/var/opt/mssql

  postgres:
    image: postgres:16
    container_name: smpt_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - smpt_postgres_data:/var/lib/postgresql/data

volumes:
  smpt_sqlserver_data:
  smpt_postgres_data: